Repository clubgamma/Ticket-Booking, pull requests merged in 2024-10, with the labels that each got.

#8 add resume ticket booking and save progress functionality
  CONTRIBUTING.md
  booking.c
  booking.exe
  bookings.dat
  partial_booking.dat
Labels: good first issue, Level 2, hacktoberfest-accepted

#9 fixes #5: Reciept Generation
  booking.c
Labels: Level 1, hacktoberfest-accepted

#12 Containerized the project for easier deployment
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  README.md
  booking.exe
Labels: good first issue, Level 2, hacktoberfest-accepted

#13 Display Price Based on Destination Instead of User Input
  booking.c
  bookings.dat
  partial_booking.dat
Labels: Level 1, hacktoberfest-accepted

#18 Accurate Price Calculation #15
  .gitignore
  booking.c
  bookings.dat
  partial_booking.dat
Labels: Level 2, hacktoberfest-accepted

#21 V19
  .gitignore
  booking.c
  bookings.dat
  partial_booking.dat
Labels: bug, hacktoberfest-accepted

#22 Added categories (e.g., standard, VIP) with different pricing structu…
  .gitignore
  booking.c
  bookings.dat
  partial_booking.dat
Labels: Level 2, hacktoberfest-accepted

#23 Implement Input validation
  booking.c
Labels: bug, hacktoberfest-accepted

#25 Implement Booking Summary..
  booking.c
Labels: Level 1, hacktoberfest-accepted

#32 Implement Input validation in Name
  booking.c
Labels: bug, hacktoberfest-accepted

#33 Exit Without Saveing
  booking.c
Labels: bug, hacktoberfest-accepted

#34 Dynamic Pricing #30
  booking.c
  bookings.dat
  partial_booking.dat
Labels: Level 3, hacktoberfest-accepted

#35 Modification or Cancellation bokking Features
  booking.c
Labels: good first issue, Level 1, hacktoberfest-accepted

#36 Report Analysis
  booking.c
Labels: Level 1, hacktoberfest-accepted

#39 Code Modularization
  booking.c
Labels: documentation, hacktoberfest-accepted

#41 solved Exit without saveing
  booking.c
Labels: bug, hacktoberfest-accepted

#40 bug in category of ticket
  booking.c
  bookings.dat
  partial_booking.dat
Labels: bug, hacktoberfest-accepted

#44 Search Bookings Bug
  booking.c
  bookings.dat
  partial_booking.dat
Labels: bug, hacktoberfest-accepted

#53 Enhance User Interface #27
  booking.c
Labels: Level 3, hacktoberfest-accepted

#56 Changed in option (3) and (4)
  booking.c
Labels: Level 1, hacktoberfest-accepted

#64 Add a feature to handle round-trip bookings
  booking.c
  bookings.dat
Labels: Level 1, hacktoberfest-accepted

#65 chat support system
  booking.c
Labels: Level 2, hacktoberfest-accepted

#67 Added Calender
  booking.c
Labels: Level 2, hacktoberfest-accepted

#69 apply promotional codes
  booking.c
Labels: Level 1, hacktoberfest-accepted

#72 Added TransportMode and Different Price for Bus and Train
  booking.c
Labels: Level 1, hacktoberfest-accepted

#74 Added Feedback
  booking.c
Labels: Level 1, hacktoberfest-accepted

#76 Correct both issue catagory and termination
  booking.c
Labels: Level 2, hacktoberfest-accepted

#80 FIX THE MENU LOGIC
  booking.c
Labels: bug, hacktoberfest-accepted

#81 Take Confimation for cancelling
  booking.c
Labels: Level 1, hacktoberfest-accepted

#83 Remove all Warning
  booking.c
Labels: bug, hacktoberfest-accepted

#86 Correct issue of mode transport
  booking.c
Labels: Level 1, hacktoberfest-accepted

#89 Fix mode bug
  booking.c
  feedbacks.dat
Labels: Level 2, hacktoberfest-accepted

#91 Fix termination error
  booking.c
  bookings.dat
  feedbacks.dat
Labels: bug, hacktoberfest-accepted

#93 Updated readme file
  README.md
Labels: documentation, hacktoberfest-accepted

#94 Optimized the recordFeedback function
  a
  booking
  booking.c
Labels: Level 1, hacktoberfest-accepted

#96 Display data according to transport mode
  booking.c
Labels: Level 1, hacktoberfest-accepted

#102 Reedem Points..
  booking.c
Labels: Level 2, hacktoberfest-accepted
